name: Deploy on push

on:
  push:
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SSH To Server 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}          
          key: ${{ secrets.SSH_PRIVATE_KEY }}          
          script: |
            ls -a
      - name: check ssh key
        run: |
          pwd
          ls -al
          ls -al ~/.ssh/
          cat ~/.ssh/id_rsa
      - name: SSH connect
        run: ssh david@34.126.154.112 "ip a"
