name: Deploy on push

on:
  push:
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.SSH_HOST }}
          #config: ${{ secrets.CONFIG }} #ssh_config; optional
          if_key_exists: fail # replace /ignore/fail; optional (defaults to fail)
      - name: check ssh key
        run: |
          pwd
          ls .ssh/
      - name: SSH connect
        run: ssh david@34.126.154.112 "ip a"
